Electrode-iOS/ELWebService

Source/Core/Request.swift
THGWebServiceTests/WebServiceTests.swift

- add `.Body` and `.BodyJSON` request options to allow raw HTTP body contents to be defined
- add unit test for encoding a JSON array as the HTTP body of a request
this PR allows the raw HTTP body to be defined for a request using the newly added request options `Option.Body` and `Option.BodyJSON`. Defining a `NSData` value for the HTTP body will override any body contents that were previously encoded as a result of request parameters. 
```
/// Defines the HTTP body contents of the HTTP request.
case Body(NSData)
/// Defines the JSON object that will be serialized as the body of the HTTP request.
case BodyJSON(AnyObject)
```
The `.BodyJSON` option serializes an `AnyObject` value via `NSJSONSerialization.dataWithJSONObject` and sets it as the HTTP body contents. Below an array is …

enable HTTP body to be set via request options

---

Source/Core/Request.swift
THGWebServiceTests/WebServiceTests.swift

add `.Body` and `.BodyJSON` request options to allow raw HTTP body contents to be defined
This is a back port of commit 49f046f4bd9c4e190eeec54321f08ec520cd13ef to address Swift 1.2 compatibility.

 add `.Body` and `.BodyJSON` request options to allow raw HTTP body contents to be defined

---

Source/Core/Request.swift
Source/Core/ServiceTask.swift
Source/Core/SessionDataTaskDataSource.swift
Source/Core/WebService.swift
THGWebService.xcodeproj/project.pbxproj
THGWebServiceTests/WebServiceTests.swift

- remove [request option API](https://github.com/TheHolyGrail/Swallow/commit/61fff95fc3c6bf340a8f25c75568b4a426b2bbe2#diff-ccdf9c56c88fdfd8d8c9f51eaa59a280L206)
- add [`ServiceTask`  methods](https://github.com/TheHolyGrail/Swallow/compare/request-option-api?expand=1#diff-0dbabe1bcb21e58eed224610cdb2bb40R85) for configuring the Request value
- remove `startTasksImmediately` from `WebService`
This is a work in progress of a cleaner API for configuring request details to address issue #9.
The request option API was removed in favor of adding chainable methods to `ServiceTask` for configuring the HTTP request.
The old syntax:
```
service
.POST("/post", 
parameters: ["foo" : "this needs percent encoded"],
options: [
.Header("Custom-Header", forName: "bar")
])
.response { data, res in
// …
```

refactor request option API

---

Source/Core/Request.swift
Source/Core/ServiceTask.swift
Source/Core/ServiceTaskResult.swift
Source/Core/SessionDataTaskDataSource.swift
Source/Core/WebService.swift
THGWebService.xcodeproj/project.pbxproj
THGWebServiceTests/WebServiceTests.swift

fixes issues #7 and #8
builds on the work done in PR https://github.com/TheHolyGrail/Swallow/pull/10
- handler blocks set by the `response()`, `responseJSON()`, and `responseError()` methods now run serially on a bg queue instead of on the main queue
- added `updateUI()` method to add response handlers to the chain that will be dispatched to the main queue
- added `updateErrorUI()` method to add error handlers to the chain that will be dispatched to the main queue
Introduces `ServiceTaskResult` enum to control how values flow through the handler chain. This allows response handlers to run on the bg thread and pass processed data to the next response handler in the chain.
- return `.Empty` to provide no processed value to the next handler
- return `.Value(AnyObject)` with an associated …

run response handlers on bg queue

---

Source/Core/Request.swift
THGWebServiceTests/RequestTests.swift

fixes an issue where request URLs would end with a `?` character when sending GET requests with empty parameters

encode request parameters only when parameters are non empty

---

ELWebService.xcodeproj/project.pbxproj
ELWebServiceTests/ELWebServiceTests-Bridging-Header.h
ELWebServiceTests/ObjCInteropTests.m
ELWebServiceTests/ServiceTask+TestUtils.swift
ELWebServiceTests/WebServiceTests.swift
README.md
Source/Core/ServiceTask+ObjC.swift
Source/Core/ServiceTask.swift
Source/Core/ServiceTaskResult.swift
Source/Core/WebService.swift
docs/Programming-Guide.md

This PR adds support for Obj-C interoperability by implementing option 3 of the [proposed solutions](https://github.com/Electrode-iOS/ELWebService/issues/21#issuecomment-178642922)
- Make `WebService` inherit from NSObject
- Make `ServiceTask` inherit from NSObject
- Add `ObjCHandlerResult` class to encapsulate result data from Obj-C handlers
- Add `ObjCResponseHandler` closure type to support adding response handlers that work with Obj-C
- Extend `ServiceTask` to add specially-named response handler methods to support adding handlers from Obj-C
- Add a `ServiceTaskResult` initializer so that a service task result value can be initialized from an `ObjCHandlerResult` value

add support for Obj-C interoperability

---

Source/Core/ServiceTask+ObjC.swift
Source/Core/ServiceTask.swift
docs/Programming-Guide.md

Because `Request.ParameterEncoding` is defined as a nested type in the `Request` struct it cannot be represented in Objective-C and therefore methods like `setParameters(parameters: [String: AnyObject], encoding: Request.ParameterEncoding)` cannot be called from Objective-C.
To work around this limitation I added a special `ServiceTask` request API for setting request parameters and their coresponding type of encoding from Obj-C.

add Obj-C request API to ServiceTask

---

ELWebServiceTests/ObjCInteropTests.m
ELWebServiceTests/WebServiceTests.swift
README.md
Source/Core/ServiceTask+ObjC.swift
Source/Core/ServiceTask.swift
docs/Programming-Guide.md

Sometimes the JSON response needs to be evaluated based on an `NSHTTPURLResponse` status code. Passing in `NSURLResponse` allows for this.

Add NSURLResponse to jsonResponseHandler

---

ELWebServiceTests/ObjCInteropTests.m
Source/Core/ServiceTask+ObjC.swift

force-downcast `updateUIObjC` handler's value to avoid silent failure.

---

ELWebServiceTests/ServiceTaskTests.swift
Source/Core/ServiceTask+ObjC.swift
Source/Core/ServiceTask.swift
docs/Programming-Guide.md

**Note:** This PR isn't ready to be merged (no tests, for example), but I thought it would make a good starting place for discussing whether this functionality should be added to the service task API.
Basically, it's a lightweight Promise-style API for the service task…
I added two new methods to the `ServiceTask` class:
- `transform()` is analogous to `Promise.then()`. It is only called if the current result _is not_ a `.Failure`. It takes the current **value** (or `nil`) and returns a new result.
- `recover()` is analogous to `Promise.catch()`. It is only called if the current result _is_ a `.Failure`. It takes the current **error** and returns a new result.
In either case, the new result can be `.Empty`, `.Value` or `.Failure` and it is used for all future handlers.
Sometimes it makes …

Add result processing handlers to `ServiceTask`

---

Source/Core/WebService.swift

Removes mention of non-existent `parameters` and `options` parameters from the web service request methods.
Ideally, I'd like to _have_ `parameters` because right now we're manually encoding some query params into the path. 😄

Correct inaccuracies in code documentation

---

ELWebServiceTests/RequestTests.swift
Source/Core/Request.swift

Fixes a discrepancy in how request "parameters" are encoded for `HEAD` and `DELETE` requests.
According to the [Programming Guide](https://github.com/Electrode-iOS/ELWebService/blob/master/docs/Programming-Guide.md#request-parameters) (emphasis mine):
> Parameters are percent encoded and appended as a query string of the request URL for **GET and HEAD** requests… For **all other** HTTP methods, parameters are sent as the request body.
But, the code was appending parameters to the query string for `GET` and `DELETE` (and _not_ `HEAD`) requests.
I know there's an open issue to change the way parameters work (#40), but it seems like this needs to be corrected, even if these new API are introduced.

Fix HEAD and DELETE parameter encoding

---

ELWebServiceTests/WebServiceTests.swift
Source/Core/Request.swift
Source/Core/WebService.swift

- Removed `baseURLString`, replaced with `baseURL`
- Added unit tests that cover more cases of the base URL and the relative URL. More clearly documenting the behavior with respect to leading and trailing forwards slashes.
- Made the `absoluteURLString(_:)` method dynamic, to allow for method replacement at runtime to facilitate testing where the URLs are redirected at runtime to a mocking server.
- Converted `Request` to use a URL internally rather than String.

Use URL as base URL rather than String

---

Source/Core/ServiceTask.swift

Previously if there were multiple `responseJSON` handlers in a service
task chain, the response body would be deserialized for each `responseJSON`
call. This allows multiple calls to reuse the same deserialized payload.

cache JSON deserialization so it can be reused in other handlers

---

ELWebService.xcodeproj/project.pbxproj
ELWebServiceTests/ServicePassthroughDelegateTests.swift
Source/Core/ServicePassthroughDelegate.swift
Source/Core/ServiceTask.swift
Source/Core/ServiceTaskMetrics.swift

Added a new metrics API, `ServiceTaskMetrics`, that provides `fetchStartDate` and `responseEndDate` time stamps. This enables us to measure the time interval between request sent and response recieved.
The design is loosely-based on iOS 10's [metrics API](https://developer.apple.com/documentation/foundation/urlsessiontasktransactionmetrics) for `URLSession`. Ideally we should move to iOS's metrics API after we drop iOS 9 support and can fully utilize it for all user sessions. I considered conditionally using iOS's metrics API for users that are running iOS 10 and up but I was concerned about collecting inconsistent metrics between our metrics implementation and the system's.

enable `ServiceTask` to collect performance metrics during execution

---

Source/Core/WebService.swift

This allows an application to do additional configuration to the URLSession used by all WebService instances that have not yet sent a request.
It is common in a typical application for consumers of WebServices to create the WebService instances before doing application wide configuration, which may lead to configuring the URLSession that all WebServices should use. Thus the session instance variable is made lazy so that individual instances don't enshrine it's value from the defaultSession until they need to actually make a request.
One common configuration task is to create a new URLSession using a URLSessionConfiguration object which specifies a value for httpAdditionalHeaders that are to be sent with every request.

Make the default URLSession modifiable within the app 

---

Source/Core/Request.swift
Source/Core/ServiceTask.swift

@angelodipaolo 
We don't have access to the urlRequest to set "httpShouldHandleCookie" property for the request.
Hence creating a public method

Provision to disable cookies for a request

---

ELWebServiceTests/ServicePassthroughDelegateTests.swift
Source/Core/ServicePassthroughDelegate.swift
Source/Core/ServiceTask.swift

This is useful for components that need to monitor the data firehose from web service responses.

Add a data parameter to didFinishCollectingTaskMetrics

---

Source/Core/ServiceTask.swift
docs/Programming-Guide.md

Adds an API for reading the response time of an individual service task. Previously, response times could only be read by reading all response times of the service via `ServiceTaskDelegate`.

add callback to read response time at the `ServiceTask` level

---

Source/Core/ServiceTask.swift
Source/Core/ServiceTaskMetrics.swift
docs/Programming-Guide.md

- Collect `responseJSON` and `updateUI` handler execution times as part of service task metrics.
- Send metrics at the end of handler queue execution so `responseJSON` and `updateUI` times can be measured first.

collect responseJSON and updateUI execution time

---

ELWebServiceTests/ServiceTaskTests.swift
Source/Core/ServiceTask.swift

[Also, add convenience setter for JSON data]
Consumers are forced to jump through hoops to take advantage of the new `Codable` APIs... e.g.
```
webService.POST(Endpoint.user.url(with: baseURL))
.setBody(bodyData)
.setHeaderValue("application/json", forName: "Content-Type")
```
```
let data = try JSONEncoder().encode(payload)
jsonObject = try JSONSerialization.jsonObject(with: data)
...
webService.POST(Endpoint.user.url(with: baseURL))
.setJSON(jsonObject)
```
With this change, the call site would be simplified to: 
```
.setJSONData(json)
```

Add ability to set custom content-type header on `ServiceTask`

---

ELWebServiceTests/ParameterEncodingTests.swift
Source/Core/Request.swift
Source/Core/ServiceTask.swift

The current implementation of ELWebService doesn't allow form data to be percent-encoded with a custom set of allowed characters. This is necessary, for example, when server-side handling of `+` and `/` characters differs. Although these are legal URL characters, if they are to be passed as data, they must be percent encoded.

Adds support for percent-encoding the body while specifying allowed characters

---

ELWebService.xcodeproj/xcshareddata/xcschemes/ELWebService.xcscheme

Fixes `Signing for "ELWebServiceTests" requires a development team. Select a development team in the project editor. (in target 'ELWebServiceTests')` error when building ELWebService dylib scheme with `xcodebuild`

avoid analyze and run steps for test target when building dylib scheme
